#!/bin/bash
# PACS
# Search for pacman packages in official repositories and AUR
# and display the results using less

searchResults=/tmp/pacs_results
query=$@

touch $searchResults

# Use 'script' to preserve colored formatting
script -qc "pacman -Ss $query" $searchResults

sed -i 1d $searchResults
read results <<< $(wc -l < $searchResults)

if [ $results != 0 ]; then
  less -r $searchResults &&

  # Give the possibility to search the AUR
  printf "\n"
  read -r -p "> Continue search in AUR? [y/N] " yn
  case $yn in
    [Yy]* ) :;;
    [Nn]* ) exit;;
    * ) exit;;
  esac

  script -qc "yaourt -Ss $query" $searchResults
  sed -i 1d $searchResults
  less -r $searchResults

# If no packages were found try searching the AUR
else
  script -qc "yaourt -Ss $query" $searchResults

  sed -i 1d $searchResults
  read results <<< $(wc -l < $searchResults)

  if [ $results != 1 ]; then
    less -r $searchResults
  else
    echo "Could not find any packages."
    exit
  fi
fi
